//
//  DATATABLE.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class DATATABLE: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _placeId: NSNumber?
    var _name: String?
    var _address1: String?
    var _address2: String?
    var _category: String?
    var _city: String?
    var _country: String?
    var _description: String?
    var _latitude: String?
    var _longitude: String?
    var _metaDescription: String?
    var _metaKeywords: String?
    var _metaTitle: String?
    var _oGBodyImages: String?
    var _oGDescription: String?
    var _oGImage: String?
    var _oGTitle: String?
    var _oGType: String?
    var _oGVideo: String?
    var _phoneNumber: String?
    var _state: String?
    var _tags: String?
    var _typeOfService: String?
    var _visible: String?
    var _website: String?
    var _zip: String?
    
    class func dynamoDBTableName() -> String {

        return "communityresourceapp-mobilehub-371634676-DATA_TABLE"
    }
    
    class func hashKeyAttribute() -> String {

        return "_placeId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_name"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_placeId" : "placeId",
               "_name" : "name",
               "_address1" : "address1",
               "_address2" : "address2",
               "_category" : "category",
               "_city" : "city",
               "_country" : "country",
               "_description" : "description",
               "_latitude" : "latitude",
               "_longitude" : "longitude",
               "_metaDescription" : "metaDescription",
               "_metaKeywords" : "metaKeywords",
               "_metaTitle" : "metaTitle",
               "_oGBodyImages" : "oGBodyImages",
               "_oGDescription" : "oGDescription",
               "_oGImage" : "oGImage",
               "_oGTitle" : "oGTitle",
               "_oGType" : "oGType",
               "_oGVideo" : "oGVideo",
               "_phoneNumber" : "phoneNumber",
               "_state" : "state",
               "_tags" : "tags",
               "_typeOfService" : "typeOfService",
               "_visible" : "visible",
               "_website" : "website",
               "_zip" : "zip",
        ]
    }
}
