//
//  USERTABLE.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class USERTABLE: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userEmail: String?
    var _userPassword: String?
    var _userActive: String?
    var _userName: String?
    
    class func dynamoDBTableName() -> String {

        return "communityresourceapp-mobilehub-371634676-USER_TABLE"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userEmail"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_userPassword"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userEmail" : "user_email",
               "_userPassword" : "user_password",
               "_userActive" : "user_active",
               "_userName" : "user_name",
        ]
    }
}
